site_name: Mellifluous Musings
site_author: mellypop
site_url: https://blog.mellypop.gay
repo_url: https://github.com/mellypop/blog
repo_name: mellypop/blog

theme:
  name: material

plugins:
  - blog
  - search
  - tags
